import csv
from POC_Python_eAdaptor import CargoWise_eAdaptor

class CargoWise_eAdaptor_PH_GEN():  
    
    def __init__(self, eAdaptor):
        self.eAdaptor = eAdaptor
        
    def main(self):
        PH_eAdaptor = self.eAdaptor
        filename = f"{self.eAdaptor.comp_code}_{self.eAdaptor.key}.BOL"
                   
        with open(f"{filename}", "a", newline='') as file:
            writer = csv.DictWriter(file, 
                                    quotechar='"',
                                    quoting=csv.QUOTE_ALL,
                                    
                                    
                                    fieldnames=[
                                        "Customs Office Code", 
                                        "Registry Number", 
                                        "Bill of Lading Number",
                                        "B/L Line Number",
                                        "B/L Sub-Line Number",
                                        "B/L Status",
                                        "Previous Document",
                                        "B/L Type",
                                        "B/L Nature Code",
                                        "Unique Reference Number",
                                        "Exporter Name",
                                        "Exporter Addres 1",
                                        "Exporter Addres 2",
                                        "Exporter Addres 3",
                                        "Exporter Addres 4",
                                        "Consignee Code",
                                        "Consignee Name", 
                                        "Consignee Address 1",
                                        "Consignee Address 2", 
                                        "Consignee Address 3", 
                                        "Consignee Address 4", 
                                        "Notify Party Code",
                                        "Notify Name",
                                        "Notify Party Address 1", 
                                        "Notify Party Address 2", 
                                        "Notify Party Address 3", 
                                        "Notify Party Address 4", 
                                        "Place of Departure",
                                        "Place of Destination",
                                        "Number of Containers",
                                        "Packing Code",
                                        "Number of Packages",
                                        "Gross Mass",
                                        "Measurement",
                                        "Shipping Marks 1",
                                        "Shipping Marks 2",
                                        "Shipping Marks 3",
                                        "Shipping Marks 4",
                                        "Shipping Marks 5",
                                        "Shipping Marks 6",
                                        "Shipping Marks 7",
                                        "Shipping Marks 8",
                                        "Shipping Marks 9",
                                        "Shipping Marks 10",
                                        "Goods Description 1",
                                        "Goods Description 2",
                                        "Goods Description 3",
                                        "Goods Description 4",
                                        "Goods Description 5",
                                        "Freight Indicator",
                                        "Freight Value",
                                        "Freight Currency",
                                        "Customs Value",
                                        "Customs Currency",
                                        "Transport Value",
                                        "Transport Currency",
                                        "Insurance Value",
                                        "Insurance Currency",
                                        "Total No. of Sub-BL",
                                        "Number of Seal",
                                        "Delivery Mode",
                                        "Information 1",
                                        "Information 2"
                                        ]) 
            writer.writeheader()
            writer.writerow({
                                        "Customs Office Code" : "", 
                                        "Registry Number" : "", 
                                        "Bill of Lading Number" :PH_eAdaptor.get_text(".//cw:Shipment//cw:WayBillNumber"),
                                        "B/L Line Number" : "",
                                        "B/L Sub-Line Number" : "",
                                        "B/L Status" : "",
                                        "Previous Document" : "",
                                        "B/L Type" : "",
                                        "B/L Nature Code" : "",
                                        "Unique Reference Number": "",
                                        "Exporter Name" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:OrganizationAddressCollection/cw:OrganizationAddress[cw:AddressType='ConsignorDocumentaryAddress']/cw:CompanyName"),
                                        "Exporter Addres 1" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:OrganizationAddressCollection/cw:OrganizationAddress[cw:AddressType='ConsignorDocumentaryAddress']/cw:Address1"),
                                        "Exporter Addres 2" : "",
                                        "Exporter Addres 3" : "",
                                        "Exporter Addres 4" : "",
                                        "Consignee Code" : "",
                                        "Consignee Name" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:OrganizationAddressCollection/cw:OrganizationAddress[cw:AddressType='ConsigneeDocumentaryAddress']/cw:CompanyName"), 
                                        "Consignee Address 1" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:OrganizationAddressCollection/cw:OrganizationAddress[cw:AddressType='ConsigneeDocumentaryAddress']/cw:Address1"),
                                        "Consignee Address 2" : "", 
                                        "Consignee Address 3" : "", 
                                        "Consignee Address 4" : "", 
                                        "Notify Party Code" : "",
                                        "Notify Name" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:OrganizationAddressCollection/cw:OrganizationAddress[cw:AddressType='NotifyPartyDocumentaryAddress']/cw:CompanyName"),
                                        "Notify Party Address 1" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:OrganizationAddressCollection/cw:OrganizationAddress[cw:AddressType='NotifyPartyDocumentaryAddress']/cw:Address1"), 
                                        "Notify Party Address 2" : "", 
                                        "Notify Party Address 3" : "", 
                                        "Notify Party Address 4" : "", 
                                        "Place of Departure" : PH_eAdaptor.get_text(".//cw:Shipment/cw:PortOfDischarge/cw:Code"),
                                        "Place of Destination" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:PortOfDestination/cw:Code"),
                                        "Number of Containers" : "",
                                        "Packing Code" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:OuterPacksPackageType/cw:Code"),
                                        "Number of Packages" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:OuterPacks"),
                                        "Gross Mass" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:TotalWeight"),
                                        "Measurement" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:TotalVolume"),
                                        "Shipping Marks 1" : "",
                                        "Shipping Marks 2" : "",
                                        "Shipping Marks 3" : "",
                                        "Shipping Marks 4" : "",
                                        "Shipping Marks 5" :" ",
                                        "Shipping Marks 6" : "",
                                        "Shipping Marks 7" : "",
                                        "Shipping Marks 8" : "",
                                        "Shipping Marks 9" : "",
                                        "Shipping Marks 10" : "",
                                        "Goods Description 1" : PH_eAdaptor.get_text(".//cw:Shipment//cw:SubShipmentCollection/cw:SubShipment/cw:GoodsDescription"),
                                        "Goods Description 2" : "",
                                        "Goods Description 3" : "",
                                        "Goods Description 4" : "",
                                        "Goods Description 5" : "",
                                        "Freight Indicator" : "",
                                        "Freight Value" : "",
                                        "Freight Currency" : "",
                                        "Customs Value" : "",
                                        "Customs Currency" : "",
                                        "Transport Value" : "",
                                        "Transport Currency" : "",
                                        "Insurance Value" : "",
                                        "Insurance Currency" : "",
                                        "Total No. of Sub-BL" : "",
                                        "Number of Seal" : "",
                                        "Delivery Mode" : "",
                                        "Information 1" : "",
                                        "Information 2" : ""
            })